dist: xenial

language: python

python:
  - "3.8"

before_install:
  - nvm install 11.1.0
  - nvm use 11.1.0

install:
  - pip install poetry
  - pip install --upgrade setuptools
  - poetry install
  - npm install --dev

script:
  - make qa
  - make tests
  - npm run gulp -- build --production
