---

common_extra_packages:
  - python-tox

django_name: resume
django_path: "/webapps/{{ django_name }}"
django_requirements_file: "{{ django_project_path }}/requirements.freeze"
django_domain_name: "{{ host_public_domain_name }}"
django_disallow_robots: no
django_project_repo_url: https://github.com/ellmetha/morganaubert-resume.git
django_ssl_only: yes
django_env_variables:
  DJANGO_INSTALL_PATH: "{{ django_path }}"
  DJANGO_SETTINGS_MODULE: "ma_project.settings.prod"
django_settings_pattern: jsonsettings
django_jsonsettings_properties:
  SECRET_KEY: "{{ secret__django_secret_key }}"
  ADMIN_URL: admin/
  DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  DB_NAME: "{{ django_db_name }}"
  DB_USER: "{{ django_db_user }}"
  DB_PASSWORD: "{{ django_db_password }}"
  DB_HOST: ""
  DB_PORT: ""
  DB_OPTIONS: {}
  ALLOWED_HOSTS: "['{{ django_domain_name }}', ] + {{ django_extra_domain_names|default([]) }}"
  EMAIL_DEV: "{{ secret__django_secret_email_dev }}"
  EMAIL_TEAM: "{{ secret__django_secret_email_team }}"
  GOOGLE_SITE_VERIFICATION_CODE: "{{ secret__google_site_verification_code }}"
