- name: Deploy the project
  hosts: all
  vars_files:
    - vars/secrets.yml
    - vars/project.yml

  roles:

    - role: common
      common_fix_sudoers: yes
      common_sudoers_file_to_remove: debian-cloud-init
      tags: ['base', ]

    - role: postgres-install

    - role: nginx
      nginx_delete_default_site: yes
      nginx_catchall_enable: yes
      nginx_override_conf: |
        server_names_hash_bucket_size 128;

    - role: certbot
      certbot_create_if_missing: yes
      certbot_create_standalone_stop_services:
        - nginx
      certbot_certs:
        - domains:
          - "{{ host_public_domain_name }}"
        - domains:
          - "{{ host_public_domain_name_redirect_from }}"
      when: host_enable_acme_ssl|default(False)
      tags: ['ssl', ]

    - role: nginx-ssl-conf
      ssl_domains:
        - "{{ host_public_domain_name }}"
        - "{{ host_public_domain_name_redirect_from }}"
      tags: ['ssl', ]

    - role: django
      tags: ['django', ]

    - role: nginx-redirect
      nginx_redirects:
        - from: "{{ host_public_domain_name_redirect_from }}"
          to: "{{ host_public_domain_name }}"
          ssl: yes
      when: host_is_the_real_thing
      tags: ['redirect', ]
